const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Dictionary,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Flash,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Plugins.TextBox,
		C3.Behaviors.Anchor,
		C3.Plugins.AJAX,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.SpeechRecognition,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Clipboard,
		C3.Plugins.SVGPicture,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.JavaScriptInEvents.BrainEvents_Event1_Act10,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.JavaScriptInEvents.BrainEvents_Event18_Act12,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.TextBox.Cnds.IsVisible,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.SpeechRecognition.Acts.RequestSpeechRecognition,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.SpeechRecognition.Acts.StopSpeechRecognition,
		C3.Plugins.SpeechRecognition.Cnds.OnSpeechRecognitionResult,
		C3.Plugins.SpeechRecognition.Exps.InterimTranscript,
		C3.Plugins.SpeechRecognition.Cnds.OnSpeechRecognitionEnd,
		C3.Plugins.SpeechRecognition.Exps.FinalTranscript,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.JavaScriptInEvents.BrainEvents_Event42_Act1,
		C3.Plugins.TextBox.Acts.SetText,
		C3.JavaScriptInEvents.BrainEvents_Event49_Act2,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.JavaScriptInEvents.BrainEvents_Event67,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrame
	];
};
self.C3_JsPropNameTable = [
	{BrainVoiceAnswer: 0},
	{BrainText: 0},
	{BrainTitle: 0},
	{BrainBinDict: 0},
	{BrainArray: 0},
	{DragDrop: 0},
	{Flash: 0},
	{Pin: 0},
	{Tween: 0},
	{BrainBack: 0},
	{BrainQuestion: 0},
	{BrainTest: 0},
	{BrainWiz: 0},
	{Anchor: 0},
	{Background: 0},
	{GoAwayBrain: 0},
	{name: 0},
	{type: 0},
	{lesson: 0},
	{RecycleBin: 0},
	{isClicked: 0},
	{GoButton2: 0},
	{Overlay: 0},
	{RecycleBinText: 0},
	{AJAX: 0},
	{Keyboard: 0},
	{Browser: 0},
	{TopTitle2: 0},
	{Mic: 0},
	{Mouse: 0},
	{SpeechRecognition: 0},
	{UserTranscript: 0},
	{TextBoxSmall: 0},
	{TypeInstead: 0},
	{TextBoxBig: 0},
	{Sprite2: 0},
	{ItemName: 0},
	{Touch: 0},
	{PointsBubble: 0},
	{PointsCounter: 0},
	{LocalStorage: 0},
	{YesButton: 0},
	{NoButton: 0},
	{Rotate: 0},
	{Confetti: 0},
	{Particles: 0},
	{ConfirmationQuestion: 0},
	{DoneButton: 0},
	{ItemInstructions: 0},
	{ExampleText: 0},
	{SpeakInstructions: 0},
	{Trophy: 0},
	{PointsText: 0},
	{BrainWiz2: 0},
	{TextBoxSideways: 0},
	{PointsMessage: 0},
	{HazardousButton: 0},
	{DonateButton: 0},
	{Sad: 0},
	{Text: 0},
	{PlanetFlipLogo: 0},
	{WasteWizardBanner: 0},
	{Congrats: 0},
	{ShareButton: 0},
	{Clipboard: 0},
	{ShareOverlay: 0},
	{CopyButton: 0},
	{CloseShareOverlay: 0},
	{Copied: 0},
	{Header: 0},
	{SubHeader: 0},
	{star: 0},
	{star1: 0},
	{compostBin: 0},
	{ewasteBin: 0},
	{trashBin: 0},
	{ewasteBinButton: 0},
	{trashBinButton: 0},
	{recycleBinButton: 0},
	{compostBinButton: 0},
	{Sprite: 0},
	{backButton: 0},
	{nextButton: 0},
	{onboardingTextBubble: 0},
	{onboardingCharImage: 0},
	{onboardingCharBubble: 0},
	{startButton: 0},
	{recycleBin1: 0},
	{nextButton2: 0},
	{binItems: 0},
	{Sprite3: 0},
	{Text2: 0},
	{Text3: 0},
	{Text4: 0},
	{quizTrashButton: 0},
	{quizRecycleButton: 0},
	{quizCompostButton: 0},
	{quizEwasteButton: 0},
	{answersBg: 0},
	{quizIcon: 0},
	{modalIncorrect: 0},
	{modalCorrect: 0},
	{bg: 0},
	{tryAgainButton: 0},
	{showAnswerButton: 0},
	{quizNext: 0},
	{mainBackground: 0},
	{Text5: 0},
	{Text6: 0},
	{nextTimeButton: 0},
	{Text7: 0},
	{Sprite4: 0},
	{shareBadge: 0},
	{doneButton1: 0},
	{infoButton: 0},
	{learnMore: 0},
	{popup: 0},
	{ProgressBar: 0},
	{ProgressBadge: 0},
	{walkthrough: 0},
	{walkthroughNext: 0},
	{skipButton: 0},
	{notWhatISaidButton: 0},
	{notFound: 0},
	{Text8: 0},
	{tryAgainButton2: 0},
	{ProgressRank: 0},
	{RankList: 0},
	{BrainAnswer: 0},
	{CurrentUserItem: 0},
	{CurrentItemCategory: 0},
	{RecycleService: 0},
	{BrainNum: 0},
	{BrainLoaded: 0},
	{UserPoints: 0},
	{TutorialIndex: 0},
	{HasPlayed: 0},
	{IsFound: 0},
	{myitem: 0},
	{myfind: 0},
	{myi: 0},
	{myi2: 0},
	{myinstructions: 0},
	{mybin: 0},
	{layername: 0}
];

self.InstanceType = {
	BrainVoiceAnswer: class extends self.ITextInstance {},
	BrainText: class extends self.ITextInstance {},
	BrainTitle: class extends self.ITextInstance {},
	BrainBinDict: class extends self.IDictionaryInstance {},
	BrainArray: class extends self.IArrayInstance {},
	BrainBack: class extends self.ISpriteInstance {},
	BrainQuestion: class extends self.ITextInstance {},
	BrainTest: class extends self.ITextInputInstance {},
	BrainWiz: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GoAwayBrain: class extends self.ISpriteInstance {},
	RecycleBin: class extends self.ISpriteInstance {},
	GoButton2: class extends self.ISpriteInstance {},
	Overlay: class extends self.ISpriteInstance {},
	RecycleBinText: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	TopTitle2: class extends self.ISpriteInstance {},
	Mic: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	SpeechRecognition: class extends self.IInstance {},
	UserTranscript: class extends self.ITextInstance {},
	TextBoxSmall: class extends self.ISpriteInstance {},
	TypeInstead: class extends self.ITextInstance {},
	TextBoxBig: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	ItemName: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	PointsBubble: class extends self.ISpriteInstance {},
	PointsCounter: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	YesButton: class extends self.ISpriteInstance {},
	NoButton: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	ConfirmationQuestion: class extends self.ITextInstance {},
	DoneButton: class extends self.ISpriteInstance {},
	ItemInstructions: class extends self.ITextInstance {},
	ExampleText: class extends self.ITextInstance {},
	SpeakInstructions: class extends self.ITextInstance {},
	Trophy: class extends self.ISpriteInstance {},
	PointsText: class extends self.ITextInstance {},
	BrainWiz2: class extends self.ISpriteInstance {},
	TextBoxSideways: class extends self.ISpriteInstance {},
	PointsMessage: class extends self.ITextInstance {},
	HazardousButton: class extends self.ISpriteInstance {},
	DonateButton: class extends self.ISpriteInstance {},
	Sad: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	PlanetFlipLogo: class extends self.ISpriteInstance {},
	WasteWizardBanner: class extends self.ISpriteInstance {},
	Congrats: class extends self.ITextInstance {},
	ShareButton: class extends self.ISpriteInstance {},
	Clipboard: class extends self.IInstance {},
	ShareOverlay: class extends self.ISpriteInstance {},
	CopyButton: class extends self.ISpriteInstance {},
	CloseShareOverlay: class extends self.ISpriteInstance {},
	Copied: class extends self.ITextInstance {},
	Header: class extends self.ITextInstance {},
	SubHeader: class extends self.ITextInstance {},
	star: class extends self.ISVGPictureInstance {},
	star1: class extends self.ISpriteInstance {},
	compostBin: class extends self.ISpriteInstance {},
	ewasteBin: class extends self.ISpriteInstance {},
	trashBin: class extends self.ISpriteInstance {},
	ewasteBinButton: class extends self.ISpriteInstance {},
	trashBinButton: class extends self.ISpriteInstance {},
	recycleBinButton: class extends self.ISpriteInstance {},
	compostBinButton: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	backButton: class extends self.ISpriteInstance {},
	nextButton: class extends self.ISpriteInstance {},
	onboardingTextBubble: class extends self.ISpriteInstance {},
	onboardingCharImage: class extends self.ISpriteInstance {},
	onboardingCharBubble: class extends self.ISpriteInstance {},
	startButton: class extends self.ISpriteInstance {},
	recycleBin1: class extends self.ISpriteInstance {},
	nextButton2: class extends self.ISpriteInstance {},
	binItems: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	quizTrashButton: class extends self.ISpriteInstance {},
	quizRecycleButton: class extends self.ISpriteInstance {},
	quizCompostButton: class extends self.ISpriteInstance {},
	quizEwasteButton: class extends self.ISpriteInstance {},
	answersBg: class extends self.ISpriteInstance {},
	quizIcon: class extends self.ISpriteInstance {},
	modalIncorrect: class extends self.ISpriteInstance {},
	modalCorrect: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	tryAgainButton: class extends self.ISpriteInstance {},
	showAnswerButton: class extends self.ISpriteInstance {},
	quizNext: class extends self.ISpriteInstance {},
	mainBackground: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	nextTimeButton: class extends self.ISpriteInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	shareBadge: class extends self.ISpriteInstance {},
	doneButton1: class extends self.ISpriteInstance {},
	infoButton: class extends self.ISpriteInstance {},
	learnMore: class extends self.ISpriteInstance {},
	popup: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.ISpriteInstance {},
	ProgressBadge: class extends self.ISpriteInstance {},
	walkthrough: class extends self.ISpriteInstance {},
	walkthroughNext: class extends self.ISpriteInstance {},
	skipButton: class extends self.ISpriteInstance {},
	notWhatISaidButton: class extends self.ISpriteInstance {},
	notFound: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	tryAgainButton2: class extends self.ISpriteInstance {},
	ProgressRank: class extends self.ISpriteInstance {},
	RankList: class extends self.ISpriteInstance {}
}